server:
  port: '0'

spring:
  # application 정보 설정
  application:
    name: user-server
  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
  #
  cloud:
    config:
      name: user-server
      profile: docker

test:
  redirect-uri: http://3.35.94.116:3000