server:
  port: 0

spring:
  # application 정보 설정
  application:
    name: user-server
  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  cloud:
    config:
      name: user-server
      profile: dev


test:
  redirect-uri: http://10.10.10.29:3000
